application.viber-bot:
 auth-token: "48c2503931a7d075-a5784049295d1520-cca8cfc397f4d93e"
 webhook-url: "https://firstbotbot.herokuapp.com/"
 name: "firstbotbot "
 avatar: "https://img.freepik.com/free-icon/dropbox_318-139793.jpg?size=338c&ext=jpg"

logging:
  level:
    root: DEBUG

